// ============================================================
// ITINERARY DATA — Kim's Family Visit to Seattle, Apr 17–21
// All times in 24-hour format (13:00 = 1 PM, etc.)
// ============================================================

const ITINERARY = [
  // ─────────────────────────────────────────────────────────
  // DAY 1 — April 17 (Friday) — Soft Landing
  // ─────────────────────────────────────────────────────────
  {
    id: 'day-1',
    date: '2026-04-17',
    dayNumber: 1,
    dayName: 'Friday',
    title: 'Soft Landing',
    subtitle: 'Just the Girls — Kyle joins for dinner',
    weather: '56°F, overcast',
    area: 'Kirkland & Bellevue',
    transport: 'No light rail today — all driving',
    emoji: '☕',
    accentColor: '#2E6B8A',
    gradientFrom: '#1a3a4a',
    gradientTo: '#2E6B8A',
    events: [
      {
        id: 'day1-arrive',
        time: '11:30',
        title: 'Settle in at Home',
        address: null,
        coords: null,
        image: 'https://cdn.discordapp.com/attachments/1049798983612112957/1494021774688391348/IMG_7196.jpg?ex=69e117b4&is=69dfc634&hm=cfc0c7b28611814130dd3fc23a25dd35de603af30912e33ae26b14a6accee80e&',
        imageX: 51.6, imageY: 40.6,
        description: 'Arrive, drop bags, freshen up. Welcome to the PNW!',
        duration: '30 min',
        cost: null,
        category: 'home',
        commute: null,
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day1-zoka',
        time: '12:30',
        title: 'Zoka Coffee',
        address: '129 Central Way, Kirkland',
        coords: { lat: 47.6823, lng: -122.2067 },
        image: 'https://www.zokacoffee.com/cdn/shop/files/Kirkland_11_1500x.jpg?v=1711067584',
        description: 'First PNW coffee. Cozy chairs, big windows downtown Kirkland.',
        duration: '30 min',
        cost: '$6–8/person',
        category: 'coffee',
        commute: { from: 'home', mode: 'drive', minutes: 5, note: '~5 min drive' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day1-marina',
        time: '13:15',
        title: 'Kirkland Marina Park',
        address: '25 Lakeshore Plaza, Kirkland',
        coords: { lat: 47.6743, lng: -122.2057 },
        image: 'https://www.kirklandwa.gov/files/assets/public/v/1/images/marinapark3retouched.jpg?dimension=pageimagefullwidth&w=1140',
        imageX: 49.5, imageY: 56.3,
        description: 'Lake Washington, the Cascades, and the Seattle skyline across the water. Flat and easy walk.',
        duration: '30 min',
        cost: 'Free',
        category: 'nature',
        commute: { from: 'day1-zoka', mode: 'walk', minutes: 3, note: '3 min walk from Zoka' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day1-beachhouse',
        time: '14:00',
        title: "Ivar's Seafood Bar",
        address: "Ivar's Seafood Bar, 5910, Lake Washington Boulevard Northeast",
        coords: { lat: 47.6605621, lng: -122.2060618 },
        image: 'https://tb-static.uber.com/prod/image-proc/processed_images/cd09e9289182522b215c4c36b04cd8f4/fb86662148be855d931b37d6c1e5fcbe.jpeg',
        description: 'A classic Seattle waterfront spot known for quick, casual seafood like fish & chips and clam chowder. Expect counter service, outdoor seating by the water, and a fun, laid-back vibe (with lots of seagulls around!). Great for a relaxed, scenic bite without a long wait.',
        duration: '~1.5 hrs',
        cost: '$13–22/person',
        category: 'restaurant',
        commute: { from: 'day1-marina', mode: 'drive', minutes: 10, note: '10 min drive' },
        reservation: true,
        reservationLink: null,
        reservationNote: 'Reservations recommended on Fridays',
      },
      {
        id: 'day1-bellevue-sq',
        time: '16:15',
        title: 'Bellevue Square Mall',
        address: '575 Bellevue Square, Bellevue',
        coords: { lat: 47.6169, lng: -122.2012 },
        image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/63/ee/3f/bellevue-square-center.jpg?w=1200&h=-1&s=1',
        description: 'Nordstrom, Zara, Anthropologie, and Pop Mart inside. Everyone browses at their own pace, no pressure.',
        duration: '~1.5 hrs',
        cost: 'Browse or buy',
        category: 'shopping',
        commute: { from: 'day1-beachhouse', mode: 'drive', minutes: 15, note: '~15 min drive' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day1-dtf',
        time: '18:00',
        title: 'Dinner — Din Tai Fung',
        address: '10455 NE 8th St, Bellevue',
        coords: { lat: 47.6147, lng: -122.1990 },
        image: 'https://www.foodandwine.com/thmb/M6EuNJTfQ3h6lCMF7Eb-P4lQoN0=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/Largest-Din-Tai-Fung-Opens-FT-BLOG0724-Food-05-621542cc39f541e9bc783e09df3b59c2.jpg',
        description: 'The most beautiful DTF location in the US. Xiao long bao, spicy wontons, braised beef noodle soup, chocolate lava buns. Kyle joins the group here for his first dinner with everyone — the perfect welcome meal.',
        duration: '~1.5 hrs',
        cost: '$25–35/person',
        category: 'restaurant',
        commute: { from: 'day1-bellevue-sq', mode: 'walk', minutes: 5, note: '5 min walk from Bellevue Square' },
        reservation: true,
        reservationLink: 'https://www.exploretock.com/dintaifungbellevuewashington',
        reservationNote: 'Reserve at dtf.com',
      },
      {
        id: 'day1-snowy',
        time: '20:00',
        title: 'Snowy Village Bellevue',
        address: '1075 Bellevue Way NE, Bellevue',
        coords: { lat: 47.6153, lng: -122.2005 },
        image: 'https://img.cdn4dd.com/cdn-cgi/image/fit=cover,width=600,height=400,format=auto,quality=80/https://doordash-static.s3.amazonaws.com/media/store/header/3317c79d-cf47-48fc-99ad-b3fc6fdb8854.jpg',
        imageX: 42.8, imageY: 80,
        description: 'Korean bingsu to end the night. Mango or taro. Share one between two. Open until 10:45 PM Fridays.',
        duration: '30 min',
        cost: '$12–15 each',
        category: 'dessert',
        commute: { from: 'day1-dtf', mode: 'walk', minutes: 5, note: '5 min walk' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // DAY 2 — April 18 (Saturday) — Jessica's Birthday 🎂
  // Pike Place Area Only
  // ─────────────────────────────────────────────────────────
  {
    id: 'day-2',
    date: '2026-04-18',
    dayNumber: 2,
    dayName: 'Saturday',
    title: "Jessica's Birthday",
    subtitle: 'Family morning · Full group at Pike Place Market',
    weather: '53°F, coolest day',
    area: 'Pike Place Market & Seattle Waterfront',
    transport: 'Light rail from Downtown Redmond Station → Westlake • $3.25/person • ~35 min',
    emoji: '🎂',
    accentColor: '#7B4F9E',
    gradientFrom: '#3a1a5a',
    gradientTo: '#7B4F9E',
    events: [
      {
        id: 'day2-thruline',
        time: '9:30',
        title: 'Thruline Coffee Co.',
        address: '136 Park Ln, Kirkland',
        coords: { lat: 47.6828, lng: -122.2063 },
        image: 'https://dynamic-media-cdn.tripadvisor.com/media/photo-o/16/a3/85/5f/photo0jpg.jpg?w=1100&h=1100&s=1',
        imageX: 43.1, imageY: 84.4,
        description: 'Birthday morning coffee with the family. Slow start before the big day.',
        duration: '30 min',
        cost: '$6–8/person',
        category: 'coffee',
        commute: null,
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-kyle-note',
        time: '~10:00',
        title: 'Kyle — Morning Haircut',
        address: null,
        coords: null,
        image: 'https://cdn.discordapp.com/attachments/1049798983612112957/1494032409807556698/A2519AEC-B5B2-4A1B-8A3E-21781DB76D75.png?ex=69e1219c&is=69dfd01c&hm=30a8a16d41dc7ed948f02fe78ec1bd452dfebf2627d31fe3fc6b6c25080bad3a&',
        imageX: 12.4, imageY: 36.9,
        description: 'Kyle is getting a haircut this morning and will meet everyone at Downtown Redmond Station around noon. Family heads out around 11:45 AM to make it to the station by noon.',
        duration: null,
        cost: null,
        category: 'home',
        commute: null,
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-redmond-station',
        time: '12:00',
        title: 'Meet at Downtown Redmond Station',
        address: '16160 NE 83rd St, Redmond (2 Line)',
        coords: { lat: 47.6748, lng: -122.1191 },
        image: 'https://upload.wikimedia.org/wikipedia/commons/9/96/Downtown_Redmond_Station_east_entrance_on_opening_day.jpg',
        imageX: 47.5, imageY: 52.5,
        description: 'Full group boards the 2 Line toward Westlake. ~35 min to downtown Seattle. Trains every 15 min on weekends — free street parking nearby.',
        duration: null,
        cost: '$3.25/person each way',
        category: 'transit',
        commute: { from: 'day2-thruline', mode: 'drive', minutes: 15, note: '~15 min drive from Kirkland' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-arrive-westlake',
        time: '12:35',
        title: 'Arrive — Westlake Station',
        address: '400 Pine St, Seattle',
        coords: { lat: 47.6107, lng: -122.3389 },
        image: 'https://media-cdn.sygictraveldata.com/media/800x600/612664395a40232133447d33247d3832353430333838',
        imageX: 46.4, imageY: 67.5,
        description: 'Westlake puts you right at the top of Pike Place Market. Short 5-min walk downhill to the main market entrance on Pike Street.',
        duration: null,
        cost: null,
        category: 'transit',
        commute: { from: 'day2-redmond-station', mode: 'transit', minutes: 35, note: '35 min light rail' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-og-starbucks',
        time: '12:45',
        title: 'Original Starbucks',
        address: '1912 Pike Place, Seattle',
        coords: { lat: 47.6099, lng: -122.3421 },
        image: 'https://i.insider.com/618adf3b23745d001825c09e?width=1200&format=jpeg',
        imageX: 41.4, imageY: 63.7,
        description: 'The first Starbucks ever — small, busy, and historic. Get your birthday coffee here. The signage inside has the original brown Starbucks mermaid logo. Usually a short line but worth it. Great photo spot.',
        duration: '20 min',
        cost: '$6–8/person',
        category: 'coffee',
        commute: { from: 'day2-arrive-westlake', mode: 'walk', minutes: 5, note: '5 min walk downhill to Pike Place' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-pike-market',
        time: '13:15',
        title: 'Pike Place Market',
        address: '85 Pike St, Seattle',
        coords: { lat: 47.6085, lng: -122.3422 },
        image: 'https://images.pikeplacemarket.org/wp-content/uploads/2021/09/21071015/pike_place_market-seattle-washington-public_market.jpg',
        imageX: 45.5, imageY: 51.9,
        description: 'Wander the main arcade and lower levels. Watch the famous flying fish toss, browse fresh flower stalls, local honey, handmade crafts. Stop at The Daily Dozen for fresh mini donuts — they fry them right in front of you. Hit the Pike Place Sundeck for sweeping Elliott Bay views.',
        duration: '1.5 hrs',
        cost: 'Free to walk — snacks $5–15',
        category: 'nature',
        commute: { from: 'day2-og-starbucks', mode: 'walk', minutes: 1, note: 'Right next door' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-gum-wall',
        time: '14:45',
        title: 'Post Alley + Gum Wall',
        address: '1428 Post Alley, Seattle',
        coords: { lat: 47.6092, lng: -122.3415 },
        image: 'https://afar.brightspotcdn.com/dims4/default/0ab1801/2147483647/strip/false/crop/2400x1647+0+0/resize/1486x1020!/quality/90/?url=https%3A%2F%2Fk3-prod-afar-media.s3.us-west-2.amazonaws.com%2Fbrightspot%2F42%2Fa7%2F1b3cd07a6799c6d8f9e05a40b88f%2Foriginal-b51668284ae14cfa2682b7ae08607002',
        imageX: 49.5, imageY: 13.8,
        description: 'The famous gum wall is right behind Pike Place — an alleyway covered floor-to-ceiling in chewed gum since the 1990s. Weird, iconic, and a great photo stop. Post Alley itself is lined with cafes and boutique shops.',
        duration: '20 min',
        cost: 'Free (bring a piece of gum)',
        category: 'nature',
        commute: { from: 'day2-pike-market', mode: 'walk', minutes: 2, note: '2 min walk through the market' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-waterfront',
        time: '15:15',
        title: 'Seattle Waterfront — Pier 57',
        address: 'Pier 57, 1301 Alaskan Way, Seattle',
        coords: { lat: 47.6064, lng: -122.3425 },
        image: 'https://images.seattletimes.com/wp-content/uploads/2025/07/06242025_itineraries_163255.jpg?d=780x527',
        description: 'Walk the newly renovated waterfront. Pier 57 has the Seattle Great Wheel (ferris wheel over the water), views of Elliott Bay, the Olympic Mountains, and ferry traffic. Low-key, breezy, and beautiful.',
        duration: '45 min',
        cost: 'Free to walk — Great Wheel $15/person optional',
        category: 'nature',
        commute: { from: 'day2-gum-wall', mode: 'walk', minutes: 5, note: '5 min walk downhill to the waterfront' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-simply-seattle',
        time: '16:15',
        title: 'Simply Seattle — Souvenirs',
        address: '1600 1st Ave, Seattle',
        coords: { lat: 47.6099, lng: -122.3433 },
        image: 'https://images.unsplash.com/photo-1472746729193-4d3e3c9fb064?auto=format&fit=crop&w=600&h=280&q=80',
        description: 'Best Seattle souvenir shop right near Pike Place. Good selection without being kitschy — Seattle-branded apparel, local snacks, and gifts. Perfect birthday shopping lap for everyone to grab something.',
        duration: '30 min',
        cost: 'Browse or buy',
        category: 'shopping',
        commute: { from: 'day2-waterfront', mode: 'walk', minutes: 8, note: '8 min walk back uphill' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day2-spinasse',
        time: '19:30',
        title: 'Birthday Dinner — Maximilien',
        address: 'Maximilien, 81 A, Pike Street',
        coords: { lat: 47.6083167, lng: -122.3408538 },
        image: 'https://lh3.googleusercontent.com/p/AF1QipMI9WwKpBoqJes12TDJpa_xpPE3cTzvT5E_v8B4=s680-w680-h510-rw',
        imageX: 47.3, imageY: 48.8,
        description: 'A charming French restaurant tucked inside Pike Place Market with one of the best waterfront views in Seattle. Known for classic dishes like escargot and duck, it offers a cozy, slightly upscale atmosphere—great for a relaxed but memorable sit-down meal with a view.',
        duration: '~2 hrs',
        cost: '~$35–$70+ per person (entrée + possible appetizer or drink)',
        category: 'restaurant',
        commute: { from: 'day2-simply-seattle', mode: 'walk', minutes: 5, note: 'Right in Pike Place Market' },
        reservation: true,
        reservationLink: 'https://www.maximilienrestaurant.com',
        reservationNote: 'Reserve and mention it\'s a birthday',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // DAY 3 — April 19 (Sunday) — Split Day
  // ─────────────────────────────────────────────────────────
  {
    id: 'day-3',
    date: '2026-04-19',
    dayNumber: 3,
    dayName: 'Sunday',
    title: 'Split Day',
    subtitle: 'Sylvia & Jennifer explore Seattle · Kim + Mom + Kyle — Bainbridge Island Ferry',
    weather: '57°F',
    area: 'Seattle (Sylvia & Jennifer) + Bainbridge Island (Kim, Mom & Kyle)',
    transport: 'Sylvia & Jennifer: Light rail from Redmond Station · Kim/Mom/Kyle: Drive to Seattle ferry terminal',
    emoji: '🌿',
    accentColor: '#2D6A4F',
    gradientFrom: '#1a3a2a',
    gradientTo: '#2D6A4F',
    events: [
      {
        id: 'day3-split-morning',
        time: '9:30',
        title: 'Morning Split — Go Your Separate Ways',
        address: null,
        coords: null,
        image: null,
        description: 'Sylvia & Jennifer head to Downtown Redmond Station for the 2 Line into Seattle. Kim, Mom, and Kyle drive to Seattle\'s Pier 52 (Coleman Dock) for the Bainbridge Island ferry. Everyone regrouping back home at 4:30 PM.',
        duration: null,
        cost: null,
        category: 'transit',
        commute: null,
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },

      // ── SYLVIA & JENNIFER ──
      {
        id: 'day3-sj-kinokuniya',
        time: '11:00',
        title: 'Kinokuniya Bookstore',
        address: '525 S Weller St, Seattle (International District)',
        coords: { lat: 47.5983, lng: -122.3265 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAHUap9H2GuUQAz9CkcB8u4GgJueJ00NDMLTF7Q3AGH_TcChUtTFpkkXH0J-poghb2VoFOwykJYJyc8OD1RaY0iH7UTLsiiE9oXouEOSTfHh3NTRWvp5NHneZE7Bv_JbvvIGbzyt=s680-w680-h510-rw',
        imageX: 48.8, imageY: 50.6,
        description: 'Best Japanese bookstore in the US. Manga, figures, stationery, plushies, limited editions. Budget 1.5 hrs.',
        duration: '1.5 hrs',
        cost: 'Browse or buy',
        category: 'shopping',
        commute: { from: 'day3-split-morning', mode: 'transit', minutes: 50, note: 'Light rail: Redmond Station → ID/Chinatown (~50 min)' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        splitGroup: 'sylvia-jennifer',
      },
      {
        id: 'day3-sj-uwajimaya',
        time: '12:30',
        title: 'Uwajimaya Food Court',
        address: '600 5th Ave S, Seattle',
        coords: { lat: 47.5980, lng: -122.3270 },
        image: 'https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=600&h=280&q=80',
        description: 'Right next to Kinokuniya. Korean corn dogs, boba, ramen, takoyaki. Budget 45 min.',
        duration: '45 min',
        cost: '$10–15/person',
        category: 'restaurant',
        commute: { from: 'day3-sj-kinokuniya', mode: 'walk', minutes: 2, note: 'Next door' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        splitGroup: 'sylvia-jennifer',
      },
      {
        id: 'day3-sj-hobobird',
        time: '14:00',
        title: 'Hobo Bird',
        address: '4733 Brooklyn Ave NE, Seattle (U District)',
        coords: { lat: 47.6617, lng: -122.3134 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAGz6Wjs1SGYRPirfJogDMdCfnDbGiNGiql0NejIyOIjbFt6VHN5gmLNGHOoue3LWWFGctwy-rUo9K5EbOqQZxkmJHEqRbShALCf4L_1Qalf4iOw66dwaQvJBRXhmdvY6sacn_yw9A=s680-w680-h510-rw',
        imageX: 47.3, imageY: 50.6,
        description: 'Niche Japanese import shop, local artist prints, anime merch. Take the 2 Line 2 stops north from Capitol Hill.',
        duration: '1 hr',
        cost: 'Browse or buy',
        category: 'shopping',
        commute: { from: 'day3-sj-uwajimaya', mode: 'transit', minutes: 20, note: '2 stops north on 2 Line' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        splitGroup: 'sylvia-jennifer',
      },

      // ── KIM + MOM + KYLE — BAINBRIDGE FERRY ──
      {
        id: 'day3-coleman-dock',
        time: '10:00',
        title: 'Drive to Pier 52 — Coleman Dock',
        address: 'Pier 52, 801 Alaskan Way, Seattle',
        coords: { lat: 47.6025, lng: -122.3393 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAFvA7AKZG_VP7bxzlJVGfZkF-6N1efjL1yWLctxqEY6AQchD_Kai4fU0UNahRDTkagfbPjIlbCrkUt1WtHdI1GqxlJU6d0pUfVakPRys7zE-Caga8PxIj2FMqzI2rGZfxorZYvr=s680-w680-h510-rw',
        imageX: 48.5, imageY: 57.5,
        description: 'Drive straight to Seattle\'s main ferry terminal on the waterfront. Free parking nearby (paid lots on Alaskan Way). The ferry terminal has a cafe inside if you need coffee before boarding.',
        duration: null,
        cost: null,
        category: 'transit',
        commute: { from: 'day3-split-morning', mode: 'drive', minutes: 35, note: '~35 min drive from Kirkland' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        splitGroup: 'kim-kyle-mom',
      },
      {
        id: 'day3-bainbridge-ferry',
        time: '11:05',
        title: 'Washington State Ferry to Bainbridge Island',
        address: 'WSF Seattle–Bainbridge Ferry, Pier 52',
        coords: { lat: 47.6025, lng: -122.3393 },
        image: 'https://res.cloudinary.com/sagacity/image/upload/c_crop,h_2727,w_3971,x_407,y_0/c_limit,dpr_auto,f_auto,fl_lossy,q_80,w_1080/shutterstock_1314929045-web_yxjub8.jpg',
        imageX: 48.1, imageY: 50.6,
        description: 'Board the Washington State Ferry — one of the most scenic short ferry rides in the world. ~35 min crossing of Puget Sound with views of downtown Seattle skyline, the Olympics ahead, and Mount Rainier on a clear day. Walk to the outer decks for photos. Ferries run every 45–90 min on Sundays.',
        duration: '35 min crossing',
        cost: '~$8.80/person each way (walk-on)',
        category: 'transit',
        commute: { from: 'day3-coleman-dock', mode: 'walk', minutes: 5, note: 'Walk to ferry boarding' },
        reservation: false,
        reservationLink: 'https://www.wsdot.wa.gov/ferries',
        reservationNote: 'Check WSF schedule at wsdot.wa.gov/ferries — walk-on passengers, no reservation needed',
        splitGroup: 'kim-kyle-mom',
      },
      {
        id: 'day3-winslow',
        time: '11:45',
        title: 'Winslow Way — Bainbridge Island',
        address: 'Winslow Way E, Bainbridge Island, WA',
        coords: { lat: 47.6240, lng: -122.5195 },
        image: 'https://images.squarespace-cdn.com/content/v1/583f9db3725e25fcd4606e97/1712205080401-Z33L5LU6A4W4NVP6XCD9/Web-1.jpg',
        imageX: 46.4, imageY: 66.9,
        description: 'A charming small-town main street just steps from the ferry dock. Indie boutiques, galleries, a great bookstore (Eagle Harbor Books), and cafes. Totally walkable, completely unhurried. This is what a perfect Pacific Northwest town looks like.',
        duration: '1 hr',
        cost: 'Browse or buy',
        category: 'shopping',
        commute: { from: 'day3-bainbridge-ferry', mode: 'walk', minutes: 5, note: '5 min walk from ferry dock' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        splitGroup: 'kim-kyle-mom',
      },
      {
        id: 'day3-bainbridge-lunch',
        time: '13:00',
        title: "Lunch on Bainbridge Island - Doc's Marina Grill",
        address: '403 Madison Ave S',
        coords: { lat: 47.6228, lng: -122.5216 },
        image: 'https://lh3.googleusercontent.com/p/AF1QipNGmCXv81fng-4bVVVUMEVFG9c0YM-arCyOS3HF=s680-w680-h510-rw',
        imageX: 48.7, imageY: 77.5,
        description: 'A cozy pub right on the waterfront with views back toward Seattle. Clam chowder, fish & chips, burgers. Casual, no rush. Outdoor deck has the best views of Eagle Harbor. Walk-in friendly for lunch.',
        duration: '~1 hr',
        cost: '$18–25/person',
        category: 'restaurant',
        commute: { from: 'day3-winslow', mode: 'walk', minutes: 5, note: '5 min walk down to the marina' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        splitGroup: 'kim-kyle-mom',
      },
      {
        id: 'day3-ferry-return',
        time: '14:30',
        title: 'Ferry Back to Seattle',
        address: 'Bainbridge Island Ferry Dock, Winslow Way',
        coords: { lat: 47.6236, lng: -122.5207 },
        image: null,
        description: 'Board the return ferry to Seattle. Same stunning views, different direction — now you\'re approaching the Seattle skyline. The drive home from Pier 52 to Kirkland takes about 30 min.',
        duration: '35 min crossing + 30 min drive home',
        cost: 'Eastbound ferry is free for foot passengers',
        category: 'transit',
        commute: { from: 'day3-bainbridge-lunch', mode: 'walk', minutes: 5, note: '5 min walk back to dock' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        splitGroup: 'kim-kyle-mom',
      },

      // ── REGROUP ──
      {
        id: 'day3-regroup',
        time: '16:30',
        title: 'Everyone Regroups',
        address: null,
        coords: null,
        image: null,
        description: 'Sylvia and Jennifer take the light rail back to Redmond Station. Kim, Mom, and Kyle drive home from Seattle. Everyone back at the house by 4:30 PM.',
        duration: null,
        cost: null,
        category: 'transit',
        commute: null,
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day3-cantinetta',
        time: '19:00',
        title: 'Dinner — Cantinetta Bellevue',
        address: '10038 Main St, Bellevue',
        coords: { lat: 47.6106, lng: -122.2010 },
        image: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=600&h=280&q=80',
        description: '4.4 stars. Authentic Italian — burrata, fresh pasta, panna cotta. Cozy and elegant. Outdoor patio feels like a movie set. Open Sundays from 5 PM.',
        duration: '~1.5 hrs',
        cost: '$30–45/person',
        category: 'restaurant',
        commute: { from: 'day3-regroup', mode: 'drive', minutes: 15, note: '~15 min from Kirkland' },
        reservation: true,
        reservationLink: null,
        reservationNote: 'Reserve in advance — call or OpenTable',
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // DAY 4 — April 20 (Monday) — Full Group Eastside Activities
  // ─────────────────────────────────────────────────────────
  {
    id: 'day-4',
    date: '2026-04-20',
    dayNumber: 4,
    dayName: 'Monday',
    title: 'Eastside Activities Day',
    subtitle: 'Full Group — All Driving',
    weather: '59°F, warming up',
    area: 'Redmond & Bellevue Eastside',
    transport: 'All driving — no light rail today',
    emoji: '🎮',
    accentColor: '#C07A2A',
    gradientFrom: '#5a3010',
    gradientTo: '#C07A2A',
    events: [
      {
        id: 'day4-tipsy-cow',
        time: '12:00',
        title: 'Lunch — DERU',
        address: 'Deru Market & Eatery, 723, 9th Avenue',
        coords: { lat: 47.6819885, lng: -122.1941397 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAHOBbhyQGSv7bCzBohBaSur8OjM1jWsxcFcXv8yWOrncm33P37D5CL33PohZ2p0BdQ_4i1J3C681qYaAegH2pCLxDxL63UK5kFwkR7vUYGqxGbqk2eX4IhuYx-YFi3LSakwtbHe=s680-w680-h510-rw',
        imageX: 48, imageY: 51.9,
        description: 'A cozy, neighborhood-style café in Kirkland known for fresh, from-scratch comfort food and one of the best brunch spots on the Eastside. Expect a casual but trendy vibe, popular dishes like their famous cinnamon rolls, salads, sandwiches, and wood-fired pizzas—and potentially a wait during peak times.',
        duration: '~1 hr',
        cost: '~$15–$30 per person (brunch/lunch items; slightly more with drinks or extras)',
        category: 'restaurant',
        commute: { from: 'home', mode: 'drive', minutes: 15, note: '~15 min from Kirkland' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day4-redmond-tc',
        time: '13:30',
        title: 'Redmond Town Center',
        address: '7525 166th Ave NE, Redmond',
        coords: { lat: 47.6717, lng: -122.1200 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAFKWsg2B4qWkqQtZX1uNLsVtUnZZ9GI4JHAsg1mgHCL_O1STxWtArbI595pX-zj1h6OMvZ7UsBw_0ArhQAgCloDyVaTS5VcDM48D1LzbcQ0aQPQ9f6ff01wFHyrGSfCVKl8MvOgjeHob6WQ=s680-w680-h510-rw',
        imageX: 46.7, imageY: 72.5,
        description: 'Outdoor open-air shopping center — walkable, fountains, benches, mix of shops and cafes. Easy and relaxed afternoon browse.',
        duration: '~1 hr',
        cost: 'Browse',
        category: 'shopping',
        commute: { from: 'day4-tipsy-cow', mode: 'walk', minutes: 5, note: '5 min walk from Tipsy Cow' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day4-4dreams',
        time: '15:00',
        title: '4 Dreams Escape Room',
        address: '15600 NE 8th St, Bellevue',
        coords: { lat: 47.6172, lng: -122.1527 },
        image: 'https://lh3.googleusercontent.com/p/AF1QipO8VLCCI_EMrOv3-eS0DsLMdO5une0K33QH0T9h=s680-w680-h510-rw',
        imageX: 44.1, imageY: 68.1,
        description: '5 stars. Fully electronic, all puzzle-based. The Jungle/Jumanji room is the most popular. Perfect for all 5 of you. No padlocks, no keys — pure logic puzzles.',
        duration: '~1.5 hrs',
        cost: '$35/person',
        category: 'activity',
        commute: { from: 'day4-redmond-tc', mode: 'drive', minutes: 15, note: '~15 min drive' },
        reservation: true,
        reservationLink: 'https://www.4dreamsescape.com',
        reservationNote: 'Book at 4dreamsescape.com',
      },
      {
        id: 'day4-cafe-snack',
        time: '16:45',
        title: 'Caffe Ladro — Snack & Coffee Break',
        address: '433 Bellevue Way NE, Bellevue',
        coords: { lat: 47.6148, lng: -122.2008 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAEhQMyyCNp7GjcJtm-svENp8I1f_XYMxLEduGVJLQ6HzuQTLa5l4qVphA-uJFK1Fb0etCIWzbu2J1wsmL1EU8rqBUL5FNuY54mqqpfKG5i1KsoWMquD8yRXv0GNU9RIGJFA_gEp4LqxI6jg=s680-w680-h510-rw',
        imageX: 42.6, imageY: 41.9,
        description: 'A cozy local Seattle-chain café right in downtown Bellevue. Great espresso drinks, pastries, sandwiches, and a good spot to sit and decompress after the escape room before heading to the park. Plenty of seating inside.',
        duration: '30–45 min',
        cost: '$6–12/person',
        category: 'coffee',
        commute: { from: 'day4-4dreams', mode: 'drive', minutes: 10, note: '~10 min drive to downtown Bellevue' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day4-bellevue-park',
        time: '17:30',
        title: 'Bellevue Downtown Park',
        address: '10201 NE 4th St, Bellevue',
        coords: { lat: 47.6132, lng: -122.2007 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAGMROgqZEGcuhDE7Fd0sSFkN_pwXLXlFBzVPcTJS8-k7EFgGJyjNzqzXfRG3jF3QvzYvLkt8G_zT2IchQDxUTalk3xNkH8MHI9PUkQoIAnS9C6p5bJqzu70a34eddbYCCFXee4=s680-w680-h510-rw',
        imageX: 43.4, imageY: 57.5,
        description: 'Half-mile loop with a waterfall and reflecting pond. Beautiful wind-down for the afternoon. Easy for Mom to walk at her own pace. The waterfall canal is especially pretty.',
        duration: '30 min',
        cost: 'Free',
        category: 'nature',
        commute: { from: 'day4-cafe-snack', mode: 'walk', minutes: 8, note: '8 min walk from Caffe Ladro' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day4-tanaka',
        time: '19:00',
        title: 'Dinner — Tanaka Ramen & Izakaya',
        address: '312 Central Way, Kirkland',
        coords: { lat: 47.6810, lng: -122.2067 },
        image: 'https://lh3.googleusercontent.com/p/AF1QipOs9NjbtSjdNSGAAHcY3AdlFUvYAav3Jpk43xXH=s680-w680-h510-rw',
        imageX: 48.3, imageY: 18.1,
        description: 'Right in downtown Kirkland. Tonkotsu ramen, izakaya small plates, gyoza, ika geso. Plenty of non-seafood options. New spot, good vibes, practically home.',
        duration: '~1.5 hrs',
        cost: '$20–30/person',
        category: 'restaurant',
        commute: { from: 'day4-bellevue-park', mode: 'drive', minutes: 15, note: '~15 min drive — practically home' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────
  // DAY 5 — April 21 (Tuesday) — Last Day 🌸
  // ─────────────────────────────────────────────────────────
  {
    id: 'day-5',
    date: '2026-04-21',
    dayNumber: 5,
    dayName: 'Tuesday',
    title: 'Last Day',
    subtitle: 'H Mart, Mini Golf & Mom\'s Farewell Dinner',
    weather: '60°F, warmest day ☀️',
    area: 'Bellevue, Redmond & Kirkland',
    transport: 'All local — driving or walking',
    emoji: '🌸',
    accentColor: '#B5496A',
    gradientFrom: '#4a1a2a',
    gradientTo: '#B5496A',
    events: [
      {
        id: 'day5-hmart',
        time: '9:00',
        title: 'H Mart Redmond',
        address: 'H Mart, 7589, 170th Avenue Northeast',
        coords: { lat: 47.6703291, lng: -122.1158026 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAHbb046OFecsY_37Il7FLFzbfkc1SpgFLwAHDZ0aXNr17g7d9QRt5hKHmma2xkkmBtwHUmW0h5Zw2eUh5IUsOc88NInBVFRF8YhP89eNgM9GjDyDC1CwxUbsGibLXplpf4S8RKR5w=s680-w680-h510-rw',
        description: 'Mom picks up everything she needs for banchan and tonight\'s dinner. Let her lead — this is her world.',
        duration: '~1 hr',
        cost: 'Groceries only',
        category: 'shopping',
        commute: null,
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day5-home-morning',
        time: '10:30',
        title: 'Home — Slow Morning',
        address: null,
        coords: null,
        image: 'https://cdn.discordapp.com/attachments/1049798983612112957/1494046055367442462/image0.jpg?ex=69e12e51&is=69dfdcd1&hm=eee01b46a1b2c485d2a94ae08438ec4c75291c04f490d87401365bbebac7a1d1&',
        imageX: 48.7, imageY: 24.4,
        description: 'Slow morning. Coffee, rest, the cats. No schedule. Mom starts prepping. Everyone recharges before the afternoon.',
        duration: '~1.5 hrs',
        cost: null,
        category: 'home',
        commute: { from: 'day5-hmart', mode: 'drive', minutes: 15, note: '~15 min drive home' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day5-lunch',
        time: '12:30',
        title: 'Lunch — The Box & Burgers Eatery',
        address: '12305 120th Ave NE, Kirkland',
        coords: { lat: 47.7052, lng: -122.1876 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAFwQq7VdvD7Di-CEhHnu6r8FzNU640V0tZBQl94_3dX7pn_gcquUZk8K2XIENF6QeGv9PECk27GZIY7ob8nRwkyCGh9QWJmx_m4fI4k8fR28oE8yS8bBC5im-rJnonBTISXWOREmgAJynk=s680-w680-h510-rw',
        imageX: 46, imageY: 70.6,
        description: '4.7 stars. Creative miso burgers, bibimbap burger, loco mocos, bao. Affordable, casual, quick. Great flavors without being overpriced.',
        duration: '~1 hr',
        cost: '$14–18/person',
        category: 'restaurant',
        commute: { from: 'day5-home-morning', mode: 'drive', minutes: 10, note: '~10 min drive' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
        altNote: 'Alt: Tanaka Ramen if you skipped it Monday',
      },
      {
        id: 'day5-minigolf',
        time: '14:00',
        title: 'Mini Golf — Redmond',
        address: '10402 Willows Rd NE, Redmond, WA 98052',
        coords: { lat: 47.6868, lng: -122.1637 },
        image: 'https://lh3.googleusercontent.com/gps-cs-s/APNQkAG50Q09_wClrJvxlZjQ39UGw1nEHVVoBV5daVfIE2H3ZJv8LJZdimwW4NJsb9MG_OPwIM7upquChS4DF7XDUGMscOEwsn1u7iNWZ9LV9_tJhD-Rh93mVzPxkJzZW8YRH22knHg=s680-w680-h510-rw',
        imageX: 48.7, imageY: 25,
        description: 'A fun mini golf outing in Redmond — perfect last-afternoon activity for the whole group. Low-key, no pressure, easy for Mom to play at her own pace.',
        duration: '~1.5 hrs',
        cost: '$10–15/person',
        category: 'activity',
        commute: { from: 'day5-lunch', mode: 'drive', minutes: 15, note: '~15 min from Kirkland' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day5-home-prep',
        time: '16:30',
        title: 'Head Home — Mom Finishes Cooking',
        address: null,
        coords: null,
        image: null,
        description: 'Everyone\'s home. Mom puts the final touches on dinner. Someone sets the table, someone makes drinks. The last evening begins.',
        duration: null,
        cost: null,
        category: 'home',
        commute: { from: 'day5-minigolf', mode: 'drive', minutes: 15, note: '~15 min drive home' },
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
      {
        id: 'day5-farewell-dinner',
        time: '19:00',
        title: "Mom's Farewell Dinner at Home",
        address: null,
        coords: null,
        image: 'https://cdn.discordapp.com/attachments/1049798983612112957/1494047342003752970/4F284988-1C7E-4D77-A8F3-857F15A88EE0.png?ex=69e12f84&is=69dfde04&hm=c10e811d8e943e59d096a2e39e0c983d3a58b14aa4efc739afa8551a61eb5572&',
        imageX: 48.9, imageY: 71.3,
        description: 'The last meal of the trip — Mom\'s banchan spread, cooked in your kitchen, around your table. This is the one they\'ll carry home to Houston.',
        duration: 'All evening',
        cost: 'Priceless',
        category: 'home',
        commute: null,
        reservation: false,
        reservationLink: null,
        reservationNote: null,
      },
    ],
  },
];

// ─────────────────────────────────────────────────────────
// RESERVATION CHECKLIST
// ─────────────────────────────────────────────────────────
const RESERVATIONS = [
  { name: 'Din Tai Fung Bellevue', day: 'Apr 17 dinner', link: 'https://www.exploretock.com/dintaifungbellevuewashington', how: 'dtf.com' },
  { name: 'Spinasse', day: 'Apr 18 dinner', link: 'https://www.spinasserestaurant.com', how: 'spinasserestaurant.com — mention birthday!' },
  { name: '4 Dreams Escape Room', day: 'Apr 20 afternoon', link: 'https://www.4dreamsescape.com', how: '4dreamsescape.com' },
  { name: 'Cantinetta Bellevue', day: 'Apr 19 dinner', link: null, how: 'Call or OpenTable' },
  { name: 'WSF Ferry Schedule', day: 'Apr 19 morning', link: 'https://www.wsdot.wa.gov/ferries', how: 'Check schedule at wsdot.wa.gov/ferries' },
];

// ─────────────────────────────────────────────────────────
// LIGHT RAIL INFO
// ─────────────────────────────────────────────────────────
const LIGHT_RAIL_INFO = {
  usedOnDays: ['day-2', 'day-3'],
  boardAt: 'Downtown Redmond Station',
  parking: 'Free street parking nearby',
  fare: '$3.25/person each way',
  payment: 'ORCA card, Apple Pay, or contactless card',
  routes: [
    { from: 'Downtown Redmond', to: 'Westlake (Pike Place)', time: '~35 min' },
    { from: 'Downtown Redmond', to: 'Capitol Hill', time: '~40 min' },
    { from: 'Downtown Redmond', to: 'ID/Chinatown', time: '~45 min' },
  ],
  frequency: 'Trains every 15 min on weekends',
};

// ─────────────────────────────────────────────────────────
// CATEGORY ICONS
// ─────────────────────────────────────────────────────────
const CATEGORY_ICONS = {
  home:      { icon: '🏠', label: 'Home' },
  coffee:    { icon: '☕', label: 'Coffee' },
  restaurant:{ icon: '🍽️', label: 'Restaurant' },
  dessert:   { icon: '🍧', label: 'Dessert' },
  shopping:  { icon: '🛍️', label: 'Shopping' },
  activity:  { icon: '🎯', label: 'Activity' },
  nature:    { icon: '🌿', label: 'Park / Nature' },
  transit:   { icon: '🚊', label: 'Transit' },
};

const TRAVEL_MODE_ICONS = {
  drive:   { icon: '🚗', label: 'Drive' },
  walk:    { icon: '🚶', label: 'Walk' },
  transit: { icon: '🚊', label: 'Light Rail' },
};
